language: csharp

mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.8.0

solution: Rational.sln

install:
  - nuget restore Rational.sln

script:
  - xbuild /p:Configuration=Debug Rational.sln
  - xbuild /p:Configuration=Release Rational.sln

after_script:
  - mono ./RationalNumberExample/bin/Debug/RationalNumberExample.exe
  - mono ./RationalNumberExample/bin/Release/RationalNumberExample.exe
  - nuget pack RationalNumber\RationalNumber.csproj