language: csharp

mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.8.0

env:
  - configuration=Debug
  - configuration = Release

solution: Rational.sln

install:
  - nuget restore Rational.sln

script:
  - xbuild /p:Configuration=$configuration Rational.sln

after_script:
  - mono ./RationalNumberExample/bin/${configuration}/RationalNumberExample.exe
  - nuget pack RationalNumber/RationalNumber.csproj