language: csharp

mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.8.0

env:
  - configuration=Debug
  - configuration = Release

solution: Rational.sln

install:
  - nuget restore Rational.sln

script:
  - if [[ $configuration == 'Debug' ]]; then xbuild /p:Configuration=Debug Rational.sln; fi
  - if [[ $configuration == 'Release' ]]; then xbuild /p:Configuration=Release Rational.sln; fi

after_script:
  - mono ./RationalNumberExample/bin/${configuration}/RationalNumberExample.exe
  - nuget

notifications:
  email: false