language: csharp

mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.8.0
  - 3.2.8
  - 2.1.10

solution: Rational.sln

install:
  - nuget restore Rational.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Rational.sln
  - mono ./testrunner/NUnit.Runners.3.4.1/tools/nunit-console.exe ./RationalNumberTest/bin/Release/RationalNumberTest.dll

after_script:
  ./RationalNumberExample/bin/Release/RationalNumberExample.exe