image: Visual Studio 2015

configuration: 
  - Debug
  - Release

matrix:
  fast_finish: false

before_build:
  nuget restore Rational.sln

build:
  parallel: true
  project: Rational.sln
  verbosity: minimal

after_build:
  - RationalNumberExample\bin\%configuration%\RationalNumberExample.exe
  - nuget pack RationalNumber\RationalNumber.csproj

test:
  assemblies:
    - RationalNumberTest\bin\$(configuration)\RationalNumberTest.dll