image: Visual Studio 2015

configuration: 
  - Debug
  - Release

matrix:
  fast_finish: false

before_build:
  nuget restore Rational.sln

build:
  parallel: true
  project: Rational.sln
  verbosity: minimal

after_build:
  - dir
  - cd RationalNumberExample\bin\
  - dir

test:
  assemblies:
    - RationalNumberTest\bin\$(configuration)\RationalNumberTest.dll