image: Visual Studio 2015

configuration: 
  - Debug
  - Release

matrix:
  fast_finish: false

before_build:
  nuget restore Rational.sln

build:
  parallel: true
  project: Rational.sln
  verbosity: minimal

after_build:
  - RationalNumberExample\bin\%configuration%\RationalNumberExample.exe
  - nuget pack RationalNumber\RationalNumber.csproj

test:
  assemblies:
    - RationalNumberTest\bin\$(configuration)\RationalNumberTest.dll

after_test:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory tools
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - dir tools\
  - dir tools\OpenCover.4.6.519\
  - dir tools\OpenCover.4.6.519\tools\
  - dir tools\NUnit.Runners.2.6.4\
  - dir tools\NUnit.Runners.2.6.4\tools\
  - tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:tools\NUnit.Runners.2.6.4\tools\nunit-console.exe -targetargs:"RationalNumberTest\bin\%configuration%\RationalNumberTest.dll /noshadow"
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "MyProject_coverage.xml"