image: Visual Studio 2015

configuration: 
  - Debug
  - Release

matrix:
  fast_finish: false

before_build:
  nuget restore Rational.sln

build:
  parallel: true
  project: Rational.sln
  verbosity: minimal

after_build:
  - ps: RationalNumberExample\bin\$env:configuration\RationalNumberExample.exe

test:
  assemblies:
    - ps: RationalNumberTest\bin\$env:configuration\RationalNumberTest.dll